### ISSUE TITLE
Restart after Update strategy

### ISSUE THREAD

**Issue by lucapalomba** [JuanRamino/comuni-service#6]
I see that the command for updating data is: 
`cd /app/ && npm run update:comuni && pm2 restart comuni-service`

So, each time the comuni was updated, the service stopped and restart.
In my opnion this is not the best way to do this, cause all the service flat out and reopen in memory all the Db, each time. Image this in a polling service. And if an error happen and the new file wasn't created? You cannot rollback or restart the service.

So i was thinking about using the `--watch` option for pm2.
Think about the procedure with this parameter. The comuni.json was update (my last PR) only if there is a true changing event. And the use of the watch parameter can drop the major part of useless "stop and start" procedure.

The problem is: 
In this scenario, you should have a static name for the Json, cause the watch parameter do the best watching for a file or a folder. So i propose to change the Env variable name for the file JSON in a static one (comuni.json) for example, in order to accomplish all the strategies i wrote before.

What about?

**Comment by JuanRamino** [comment]
Restarting the service each time __update:comuni__ is made is useless if data doesn't change.

Now `pm2 restart` is made by the node script directly, only when need.

Thanks Luca
